site_name: 'Backstage Custom'
site_description: 'Main documentation for Backstage features and platform APIs'
repo_url: https://github.com/oscka/backstage-custom
edit_uri: edit/main/docs


plugins:
  - techdocs-core

# For sidebar navigation on https://backstage.io/, see `microsite/sidebars.json`
nav:
  - Introduction: index.md
  - Getting Started:
      - Getting Started: 'getting-started/getting-started.md'
      - Make App: 'getting-started/make-app.md'
  - Core Features:
      - Software Catalog: 'software-catalog.md'
      - Software Templates: 'software-templates.md'
      - Kubernetes: 'kubernetes.md'
      - TechDocs: 'techdocs.md'
  - Plugins: 'plugins.md'
  - Local Development:
      - Configuration: 'local-dev/for-backstage-develop.md'
      - Develop: 'local-dev/local-develop.md'




